django/0820_crud/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path("index/", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("new/", views.new, name="new"),
    path("<int:pk>/detail/", views.detail, name="detail"),
    path("<int:pk>/edit/", views.edit, name="edit"),
    path("<int:pk>/update/", views.update, name="update"),
    path("<int:pk>/delete/", views.delete, name="del"),
]

django/0820_crud/crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

django/0820_crud/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return self.title

django/0820_crud/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
# Create your views here.

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request, 'articles/index.html', context)

def create(request):
    return render(request, 'articles/create.html')

def new(request):
    # print(request.POST)
    # print(request.POST.get('title'))
    # print(request.POST.get('content'))

    # 1번 방법
    # article = Article()
    # article.title = request.GET.get('title')
    # article.content = request.GET.get('content')
    # article.save()
    # create에서 입력 후 index가보면 맨 밑에 입력값이 추가됨

    # 2번 방법
    # title = request.GET.get('title')
    # content = request.GET.get('content')
    # article = Article(title=title, content=content)
    # article.save()

    # 3번 방법
    title = request.POST.get('title')
    content = request.POST.get('content')

    Article.objects.create(title=title, content=content)

    # return render(request, 'articles/new.html')
    return redirect('articles:index')

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        "article" : article,
    }
    return render(request, 'articles/detail.html', context)

def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        "article" : article,
    }
    return render(request, 'articles/edit.html', context)

def update(request, pk):
    edit_data = Article.objects.get(pk=pk)

    edit_data.title = request.POST.get('title')
    edit_data.content = request.POST.get('content')

    edit_data.save()

    return redirect('articles:detail', edit_data.pk)

def delete(request, pk):
    del_data = Article.objects.get(pk=pk)
    del_data.delete()

    return redirect('articles:index')

django/0820_crud/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
<form action="{%url 'articles:new' %}" method="POST">
  {% csrf_token %}
  Title : <input type="text" name="title" id="">
  <br>
  Content : <Textarea name="content">
  </Textarea>
  <br>
  <button>제출</button>
</form>


{% endblock %}

django/0820_crud/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>Detail Page</h1>
<p>제목 : {{ article.title }}</p>
<p>내용 : {{ article.content }}</p>

<a href="{% url 'articles:edit' article.pk %}">수정하기</a>
<a href="{% url 'articles:del' article.pk %}">삭제하기</a>
{% endblock %}

django/0820_crud/articles/templates/articles/edit.html
{% extends 'base.html' %}
{% block content %}
<h1>수정하기 페이지</h1>
<form action="{% url 'articles:update' article.pk %}" method="POST">
  {% csrf_token %}
  제목 : <input type="text" name="title" value="{{ article.title }}">
  <br>
  내용 : <textarea name="content">{{ article.content }}</textarea>
  <button>수정하기</button>
</form>

{% endblock %}

django/0820_crud/articles/templates/articles/index.html
{% extends 'base.html' %}
{% block content %}
<h1>index page</h1>
{% for article in articles %}
  <p>글 제목 : <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></p>
  <p>내용 : {{ article.content }}</p>
  <p>생성일 : {{ article.created_at }}</p>
  <p>수정일 : {{ article.updated_at }}</p>

{% endfor %}


{% endblock %}

django/0820_crud/articles/templates/articles/new.html
{% extends 'base.html' %}
{% block content %}
<h1>새 글 생성</h1>

{% endblock %}

django/0820_crud/crud/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>